//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RP_realtorsPortalEntities : DbContext
    {
        public RP_realtorsPortalEntities()
            : base("name=RP_realtorsPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RP_cities> RP_cities { get; set; }
        public virtual DbSet<RP_membership> RP_membership { get; set; }
        public virtual DbSet<RP_property> RP_property { get; set; }
        public virtual DbSet<RP_propertyTypes> RP_propertyTypes { get; set; }
        public virtual DbSet<RP_states> RP_states { get; set; }
        public virtual DbSet<RP_userRoles> RP_userRoles { get; set; }
        public virtual DbSet<RP_users> RP_users { get; set; }
    }
}
