//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class RP_membership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RP_membership()
        {
            this.RP_users = new HashSet<RP_users>();
        }
    
        public int m_id { get; set; }
        public string m_name { get; set; }
        public string m_features { get; set; }
        public string m_icon { get; set; }

        public HttpPostedFileBase membershipImageData { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_users> RP_users { get; set; }
    }
}
