//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class RP_property
    {
        public int p_id { get; set; }
        public Nullable<int> p_type { get; set; }
        public string p_name { get; set; }
        public long p_demand { get; set; }
        public string p_description { get; set; }
        public string p_purpose { get; set; }
        public int p_area { get; set; }
        public int p_size { get; set; }
        public int p_bedrooms { get; set; }
        public int p_bathrooms { get; set; }
        public int p_floors { get; set; }
        public int p_garages { get; set; }
        public string p_location { get; set; }
        public Nullable<int> p_city { get; set; }
        public string p_availability { get; set; }
        public Nullable<int> p_postedBy { get; set; }
        public string p_video { get; set; }
        public string p_image_1 { get; set; }
        public string p_image_2 { get; set; }
        public string p_image_3 { get; set; }
        public string p_status { get; set; }
        public System.DateTime p_created { get; set; }

        public HttpPostedFileBase ImageData1 { get; set; }
        public HttpPostedFileBase ImageData2 { get; set; }
        public HttpPostedFileBase ImageData3 { get; set; }

        public virtual RP_cities RP_cities { get; set; }
        public virtual RP_users RP_users { get; set; }
        public virtual RP_propertyTypes RP_propertyTypes { get; set; }
    }
}
