//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtors_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class RP_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RP_users()
        {
            this.RP_property = new HashSet<RP_property>();
        }
    
        public int u_id { get; set; }
        public Nullable<int> u_role { get; set; }
        public string u_name { get; set; }
        public string u_username { get; set; }
        public string u_email { get; set; }
        public string u_password { get; set; }
        public string u_phone { get; set; }
        public Nullable<int> u_city { get; set; }
        public string u_status { get; set; }
        public int u_token { get; set; }
        public System.DateTime u_created { get; set; }
        public string u_image { get; set; }
        public string u_facebook { get; set; }
        public string u_twitter { get; set; }
        public string u_instagram { get; set; }
        public string u_about { get; set; }
        public Nullable<int> u_membership { get; set; }

        public HttpPostedFileBase userImageData { get; set; }

        public virtual RP_cities RP_cities { get; set; }
        public virtual RP_membership RP_membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_property> RP_property { get; set; }
        public virtual RP_userRoles RP_userRoles { get; set; }
    }
}
